//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Resources.LibsAndDitcionary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Itinerary()
        {
            this.Race = new HashSet<Race>();
        }
    
        public int ItinaryID { get; set; }
        public int DeparturePoint { get; set; }
        public int ArrivalPoint { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual Destination Destination1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Race> Race { get; set; }
    }
}
