//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Resources.LibsAndDitcionary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketID { get; set; }
        public int BuyerID { get; set; }
        public int RaceID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal Price { get; set; }
        public string Commentary { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Race Race { get; set; }
    }
}
